---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.6

suites:
  - name: default
    run_list:
      - recipe[site-otrstypo3org::default]
    attributes:
      mysql:
        server_root_password: root
      otrs:
        fqdn: otrs.vagrant
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
      - ["private_network", {ip: "192.168.34.36"}]
