---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
    run_list:
    - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[site-otrstypo3org::default]
    attributes:
      mysql:
        server_root_password: root
      site-otrstypo3org:
        ssl_certificate: wildcard.vagrant
      otrs:
        fqdn: otrs.vagrant
        version: 5.0.3
        apache:
          ssl_cert: /etc/ssl_certs/wildcard.vagrant.crt
          ssl_key: /etc/ssl_certs/wildcard.vagrant.key
    driver_config:
      network:
      - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
      - ["private_network", {ip: "192.168.34.36"}]
